services:
  clamav-maldet:
    build: .
    container_name: clamav-maldet
    environment:
      - SCAN_TIME=0 2 * * *
      - SCAN_PATH=/scan
    volumes:
      - /path/to/your/data:/scan:ro
      - /path/to/quarantine:/usr/local/maldetect/quarantine
    ports:
      - "8888:8888"
